/**
 * Generic, folder-driven collections for the vault-synced site.
 *
 * Content is generated by `scripts/sync-vault.mjs`, which stamps every page
 * with `vault: true` and a `section` (top-level vault folder slug). Collections
 * here just group/sort those pages — no case/series-specific logic.
 */

/** Eleventy collection API slice we use. */
type CollectionApi = {
  getFilteredByGlob: (glob: string) => Item[];
};

type Item = {
  data: Record<string, unknown>;
  url?: string;
  date?: Date;
};

function dateMs(i: Item): number {
  return i.date ? i.date.getTime() : 0;
}

function sortByTitle(a: Item, b: Item): number {
  return String(a.data.title ?? "").localeCompare(
    String(b.data.title ?? ""),
    "en",
    { sensitivity: "base" },
  );
}

/** Sort key that ignores a leading "The " so "The Gate" alphabetizes under G. */
function titleKey(i: Item): string {
  return String(i.data.title ?? "").replace(/^the\s+/i, "");
}

function sortByTitleIgnoringThe(a: Item, b: Item): number {
  return titleKey(a).localeCompare(titleKey(b), "en", { sensitivity: "base" });
}

function orderOf(i: Item): number {
  const o = i.data.order;
  return typeof o === "number" ? o : Number.MAX_SAFE_INTEGER;
}

/** Explicit front-matter `order` first (ascending), then title for ties. */
function byOrderThenTitle(a: Item, b: Item): number {
  const oa = orderOf(a);
  const ob = orderOf(b);
  return oa !== ob ? oa - ob : sortByTitle(a, b);
}

/** "chorari-ledger" → "Chorari Ledger". */
function humanizeSection(slug: string): string {
  return slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export default {
  /** Session logs (chorari-ledger/daybook), newest first. Drives home + RSS. */
  sessions(api: CollectionApi) {
    return api
      .getFilteredByGlob("**/chorari-ledger/daybook/**/*.md")
      .sort((a, b) => dateMs(b) - dateMs(a));
  },

  /** Every synced lore page, alphabetical. Drives the paginated /lore/ listing. */
  lore(api: CollectionApi) {
    return api
      .getFilteredByGlob("**/*.md")
      .filter((i) => i.data.vault === true && i.data.section === "lore")
      .sort(sortByTitle);
  },

  /**
   * Campaign-guide pages (lore/Igniting the Spark), in numbered file order, for
   * the auto-generated index in the campaign.njk sidebar.
   */
  campaign(api: CollectionApi) {
    return api
      .getFilteredByGlob("**/*.md")
      .filter(
        (i) =>
          i.data.vault === true &&
          String(i.url ?? "").startsWith("/lore/igniting-the-spark/"),
      )
      .sort(byOrderThenTitle);
  },

  /**
   * Every map page in one alphabetical "Locations" group for the map.njk
   * sidebar. The vault flattened maps into `maps/locations/`, so there are no
   * sub-folders left to bucket by; titles sort ignoring a leading "The".
   */
  mapGroups(api: CollectionApi) {
    const pages = api
      .getFilteredByGlob("**/*.md")
      .filter((i) => i.data.vault === true && i.data.section === "maps")
      .sort(sortByTitleIgnoringThe);
    return pages.length ? [{ title: "Locations", pages }] : [];
  },

  /** Every synced page grouped by top-level section, for the home index. */
  sections(api: CollectionApi) {
    const pages = api
      .getFilteredByGlob("**/*.md")
      .filter((i) => i.data.vault === true);
    const map = new Map<string, Item[]>();
    for (const p of pages) {
      const section = String(p.data.section ?? "");
      if (!section) continue;
      const bucket = map.get(section);
      if (bucket) bucket.push(p);
      else map.set(section, [p]);
    }
    return Array.from(map.entries())
      .map(([slug, items]) => ({
        slug,
        title: humanizeSection(slug),
        pages: items.sort(sortByTitle),
      }))
      .sort((a, b) =>
        a.title.localeCompare(b.title, "en", { sensitivity: "base" }),
      );
  },
};
