/**
 * Generic, folder-driven collections for the vault-synced site.
 *
 * Content is generated by `scripts/sync-vault.mjs`, which stamps every page
 * with `vault: true` and a `section` (top-level vault folder slug). Collections
 * here just group/sort those pages — no case/series-specific logic.
 */

/** Eleventy collection API slice we use. */
type CollectionApi = {
  getFilteredByGlob: (glob: string) => Item[];
};

type Item = {
  data: Record<string, unknown>;
  url?: string;
  date?: Date;
};

function dateMs(i: Item): number {
  return i.date ? i.date.getTime() : 0;
}

function sortByTitle(a: Item, b: Item): number {
  return String(a.data.title ?? "").localeCompare(
    String(b.data.title ?? ""),
    "en",
    { sensitivity: "base" },
  );
}

/** "chorari-ledger" → "Chorari Ledger". */
function humanizeSection(slug: string): string {
  return slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export default {
  /** Session logs (chorari-ledger/daybook), newest first. Drives home + RSS. */
  sessions(api: CollectionApi) {
    return api
      .getFilteredByGlob("**/chorari-ledger/daybook/**/*.md")
      .sort((a, b) => dateMs(b) - dateMs(a));
  },

  /** Every synced page grouped by top-level section, for the home index. */
  sections(api: CollectionApi) {
    const pages = api
      .getFilteredByGlob("**/*.md")
      .filter((i) => i.data.vault === true);
    const map = new Map<string, Item[]>();
    for (const p of pages) {
      const section = String(p.data.section ?? "");
      if (!section) continue;
      const bucket = map.get(section);
      if (bucket) bucket.push(p);
      else map.set(section, [p]);
    }
    return Array.from(map.entries())
      .map(([slug, items]) => ({
        slug,
        title: humanizeSection(slug),
        pages: items.sort(sortByTitle),
      }))
      .sort((a, b) =>
        a.title.localeCompare(b.title, "en", { sensitivity: "base" }),
      );
  },
};
